ALTER TABLE cases ADD COLUMN case_number TEXT NOT NULL DEFAULT '';
ALTER TABLE cases ADD COLUMN ticket_number TEXT NOT NULL DEFAULT '';
ALTER TABLE cases ADD COLUMN examiner_name TEXT NOT NULL DEFAULT '';
ALTER TABLE cases ADD COLUMN organization TEXT NOT NULL DEFAULT '';
ALTER TABLE cases ADD COLUMN salt BLOB;
ALTER TABLE cases ADD COLUMN encrypted_key BLOB;
